### ISSUE TITLE
三星Watch4 Classic卡片闪退

### ISSUE THREAD

**Issue by Creatoria** [sky130/MiWu#23]
三星Watch4 Classic，已登录到米家，并添加设备收藏。
添加卡片到主页后，显示“暂无未添加内容”；长按卡片并编辑，显示标题“修改收藏”，气泡提示“左滑删除设备”，但列表显示为空，几秒后闪退回主页。log如下：
```
java.lang.IllegalStateException
----------------
App Version: 2.0.6_8
OS Version: 13_33
Vendor: samsung
Model: SM-R890
CPU ABI: [armeabi-v7a, armeabi]
----------------
java.lang.IllegalStateException: Don't miss BindingClass
	at kndroidx.recycler.live.LiveAdapter.getItemViewType(Unknown Source:74)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(Unknown Source:640)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source:5)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(Unknown Source:57)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:48)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:818)
	at androidx.wear.widget.WearableLinearLayoutManager.onLayoutChildren(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:73)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(Unknown Source:124)
	at androidx.recyclerview.widget.RecyclerView$1.run(Unknown Source:315)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1286)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1294)
	at android.view.Choreographer.doCallbacks(Choreographer.java:922)
	at android.view.Choreographer.doFrame(Choreographer.java:850)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1269)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7962)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

**Comment by sky130** [comment]
可能是混淆导致的问题

**Comment by sky130** [comment]
已在 ca51065 修复
