### ISSUE TITLE
[Feature Request] Crash on device 小爱音响 page. 在小爱音响设备界面崩溃。

### ISSUE THREAD

**Issue by Keritial** [sky130/MiWu#25]
目前在小爱音响设备界面会崩溃。

错误报告：
```
java.lang.ClassCastException
----------------
App Version: 2.0.6_8
OS Version: 14_34
Vendor: Xiaomi
Model: Mi 10
CPU ABI: [arm64-v8a, armeabi-v7a, armeabi]
----------------
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at com.github.miwu.miot.widget.VolumeSeekBar.onValueChange(Unknown Source:5)
	at com.github.miwu.miot.manager.MiotDeviceManager$refreshValue$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8770)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2590cd3, Dispatchers.IO]

```

设备：OPPO Watch SE （在手表上崩溃后就在手机上试了）

米家 app 设备页面：
![Screenshot_2024-05-20-03-08-32-690_com xiaomi smarthome](https://github.com/sky130/MiWu/assets/50075277/e2f6136e-d8e8-4517-bf93-55bff1be50a3)
![Screenshot_2024-05-20-03-03-06-498_com xiaomi smarthome](https://github.com/sky130/MiWu/assets/50075277/02ee97bb-6e64-41c1-a28b-77d6d90fc0fd)

控制中心的小米设备中心：
![Screenshot_2024-05-20-03-11-56-104_com milink service](https://github.com/sky130/MiWu/assets/50075277/d51508b6-01be-4c73-906f-69bc93022d9e)

**Comment by sky130** [comment]
这是糟糕的
