### ISSUE TITLE
收藏页面显示不全，并且会闪退

### ISSUE THREAD

**Issue by sky130** [sky130/MiWu#30]
![8be763e12f092c1cb76fc5c977adaee4.jpeg](https://github.com/sky130/MiWu/assets/64515462/0360c969-c6df-42b1-97e4-bc7c672c0113)

---

日志如下
```
java.lang.IndexOutOfBoundsException
----------------
App Version: 2.0.7_9
OS Version: 14_34
Vendor: Xiaomi
Model: 23049RAD8C
CPU ABI: [arm64-v8a, armeabi-v7a, armeabi]
----------------
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.remove(ArrayList.java:511)
	at com.github.miwu.ui.favorite.EditFavoriteActivity$liveAdapter$2$3$3.invoke(SourceFile:3)
	at com.github.miwu.ui.favorite.EditFavoriteActivity$liveAdapter$2$3$3.invoke(SourceFile:1)
	at kndroidx.recycler.live.LiveAdapter$TouchCallback.onSwiped(SourceFile:18)
	at androidx.core.app.ActivityCompat$1.run(SourceFile:91)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

**Comment by AuTsing** [comment]
同样遇到闪退的问题，但日志应该不是这个日志吧

这个日志设备是 23049RAD8C 吧

**Comment by sky130** [comment]
> 同样遇到闪退的问题，但日志应该不是这个日志吧
> 
> 这个日志设备是 23049RAD8C 吧

有关的日志

**Comment by cgcel** [comment]
pixel watch 2 也会遇到这个问题
