### ISSUE TITLE
OPPO Watch4Pro 登录闪退，闪退日志已上传

### ISSUE THREAD

**Issue by mieliou** [sky130/MiWu#8]
[Uploading 1708527241374.log…]()

**Comment by mieliou** [comment]
java.lang.IllegalArgumentException
----------------
App Version: 2.0.3_5
OS Version: 11_30
Vendor: QUALCOMM
Model: OWW221
CPU ABI: [armeabi-v7a, armeabi]
----------------
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for 
	at okhttp3.HttpUrl$Builder.parse$okhttp(Unknown Source:761)
	at okhttp3.HttpUrl$Companion.get(SourceFile:1)
	at okhttp3.Request$Builder.url(SourceFile:2)
	at miot.kotlin.MiotManager.getResponse(Unknown Source:14)
	at miot.kotlin.MiotManager.getResponse$default(Unknown Source:5)
	at miot.kotlin.MiotManager$login$2.invokeSuspend(Unknown Source:293)
	at miot.kotlin.MiotManager$login$2.invoke(SourceFile:2)
	at miot.kotlin.MiotManager$login$2.invoke(SourceFile:1)
	at okio.Okio.startUndispatchedOrReturn(Unknown Source:4)
	at kotlin.ResultKt.withContext(Unknown Source:73)
	at miot.kotlin.MiotManager.login(Unknown Source:8)
	at com.github.miwu.ui.login.dialog.LoadingDialog$init$1.invokeSuspend(Unknown Source:47)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dc17d50, Dispatchers.IO]

**Comment by sky130** [comment]
请根据应用内使用说明第一项进行操作
